export const FETCH_ALL_CONTACTS_REQUEST = 'FETCH_ALL_CONTACTS_REQUEST';
export const FETCH_ALL_CONTACTS_SUCCESS = 'FETCH_ALL_CONTACTS_SUCCESS';
export const FETCH_ALL_CONTACTS_FAIL = 'FETCH_ALL_CONTACTS_FAIL';

export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAIL = 'FETCH_CONTACT_FAIL';

export const REGISTER_CONTACT_REQUEST = 'REGISTER_CONTACT_REQUEST';
export const REGISTER_CONTACT_SUCCESS = 'REGISTER_CONTACT_SUCCESS';
export const REGISTER_CONTACT_FAIL = 'REGISTER_CONTACT_FAIL';

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
