export const FETCH_ALL_CONTACTS_REQUEST = 'FETCH_ALL_CONTACTS_REQUEST';
export const FETCH_ALL_CONTACTS_SUCCESS = 'FETCH_ALL_CONTACTS_SUCCESS';
export const FETCH_ALL_CONTACTS_FAIL = 'FETCH_ALL_CONTACTS_FAIL';